### PR TITLE
Fix `error: The source specified has already been added to the list of available package sources. Provide a unique source.`

### PR DESCRIPTION
**Pull request by amoraitis**
Skip adding nugetSource, if it is already there.

Hi @Rebel028 , Can you please review this and let me know if it's OK to merge?

Detailed error resolved by this PR.

```
Usage: dotnet nuget enable source [arguments] [options]

Arguments:
  name  Name of the source.

Options:
  --configfile  The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help     Show help information

Project Filepath: ***/***.csproj
Version Filepath: ***/***.csproj
Version Regex: /^\s*<Version>(.*)<\/Version>\s*$/m
Version: 0.0.1
Package Name: ***
This is GPR, changing url for versioning...
https://nuget.pkg.github.com/***/download/***/index.json
Status code: 401: Unauthorized
Error: 😭 error: 401: Unauthorized
/home/runner/work/_actions/Rebel028/publish-nuget/v2.6.0/index.js:44
        throw new Error(msg)
        ^

Error: error: 401: Unauthorized
    at Action._printErrorAndExit (/home/runner/work/_actions/Rebel028/publish-nuget/v2.6.0/index.js:44:15)
    at ClientRequest.<anonymous> (/home/runner/work/_actions/Rebel028/publish-nuget/v2.6.0/index.js:165:21)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
```

### CODE REVIEW

**Comment by amoraitis** [comment]
Also, can you please let me know whether I have to link it with an issue created [here](https://github.com/brandedoutcast/publish-nuget) or not?

**Comment by Rebel028** [comment]
Hi @amoraitis! 

Your changes are acceptable, but seems that they are not the reason for the error message  you get. 

First of all, this Action written in such way that errors in NuGet CLI do not affect the workflow itself. If you try to add a nuget source that already exists it will print error message but the Action execution continues. 

You get 401 response from github registry because you either use invalid credentials or really don't have a permission to push to the selected package repository. In first case, check the data you set for inputs NUGET_KEY and GITHUB_USER.

In your case (pushing to GPR) NUGET_KEY should be either [access token](https://github.com/settings/tokens) or password of a user who is authorized to push to this package repository and GITHUB_USER shoud be this user's login. If you do not set GITHUB_USER value the action will use username of **a person who triggered the action.** That person may not have a correct permissions.

P.S. You may reference an issue from https://github.com/brandedoutcast/publish-nuget here in comments, if you like. I'm not sure if you able to link it, since it's in different repo.

**Comment by amoraitis** [comment]
Thanks for your reply @Rebel028. I have already used this action in another internal repo and it seems to be working fine. The only difference with this one is that I add the same source with the Github action like this:

``` 
name: Setup .NET Core
uses: actions/setup-dotnet@v1
with:
  dotnet-version: '3.1.402'
  source-url: https://nuget.pkg.github.com/***/index.json
env:
  NUGET_AUTH_TOKEN: ${{secrets.PACKAGES_API_KEY}}
```

So I assume the root cause of the error is that the source is already there. I am pretty sure that skipping adding the feed is the way to go here. The CLI will throw an error if the source exists and the code I have seen in the js file doesn't catch errors at that point.

I will also double-check your theory that it might be an authentication issue, but I have been using the same keys, files, etc. with my succeeding workflow.

**Comment by Rebel028** [comment]
> The CLI will throw an error if the source exists and the code I have seen in the js file doesn't catch errors at that point.

That is true, but origin of this error is outside the scope of JS code, it is CLI that throws it, not JS. The code treats cli error as simple output message.

I'll merge your pull request, if you like, and you'll see for yourself. You can tag me if you'll find anything out.

**Comment by amoraitis** [comment]
That's true about js and the cli. Anyway thank you!

Will you publish it anytime soon? I am planning to use this code to fix my issue.

**Comment by Rebel028** [comment]
You don't have to wait for me to publish it. You can always use code from any commit:
 `uses: Rebel028/publish-nuget@303a8b8c070b46bc3a1f32a97c0930fbc9f17027`
or directly from master branch at HEAD:
`uses: Rebel028/publish-nuget@master`

**Comment by amoraitis** [comment]
Oh, that's pretty nice and insightful. Thank you!

**Pull request merged**
